// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Profile': string;
  'Profile__edit': string;
  'Profile__form': string;
  'Profile__header': string;
  'Profile__submit': string;
  'Profile__title': string;
}
export const cssExports: CssExports;
export default cssExports;
