// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Users': string;
  'Users__Count': string;
  'Users__Title': string;
}
export const cssExports: CssExports;
export default cssExports;
