// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Loader': string;
  'rotating': string;
}
export const cssExports: CssExports;
export default cssExports;
