// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Card': string;
  'Card__Data': string;
  'Card__Info': string;
  'Card__Link': string;
  'Card__Text': string;
}
export const cssExports: CssExports;
export default cssExports;
