// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Sort': string;
  'Sort__City': string;
  'Sort__Company': string;
  'Sort__Title': string;
}
export const cssExports: CssExports;
export default cssExports;
