// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ProfileForm': string;
  'ProfileForm__error': string;
  'ProfileForm__field': string;
  'ProfileForm__inactiveSubmit': string;
  'ProfileForm__submit': string;
  'ProfileForm__uneditableField': string;
}
export const cssExports: CssExports;
export default cssExports;
